service:
  name: serverless-expense-tracker-app

plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-iam-roles-per-function
  - serverless-es-logs

# Uncomment to enable individual packaging
package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  tracing:
    lambda: true
    apiGateway: true

  environment:
    TRANSACTIONS_TABLE: Transactions-${self:provider.stage}
    USERID_INDEX: UserIdIndex
    IMAGES_S3_BUCKET: serverless-expense-tracker-images-pvsm-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    ES_ENDPOINT: !GetAtt ImagesSearch.DomainEndpoint 

  logs:
    restApi: true

functions:
  - ${file(src/lambda/http/createTransaction.yml)}
  - ${file(src/lambda/http/deleteTransaction.yml)}
  - ${file(src/lambda/http/updateTransaction.yml)}
  - ${file(src/lambda/http/getTransactions.yml)}
  - ${file(src/lambda/http/generateUploadUrl.yml)}
  - ${file(src/lambda/http/searchTransactions.yml)}
  - ${file(src/lambda/http/getAccountBalance.yml)}
  - ${file(src/lambda/dynamoDb/elasticSearchSync.yml)}
  - ${file(src/lambda/auth/auth0Authorizer.yml)}

custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: Todo API
        description: Serverless application for expenses tracking
    models:
      - name: TransactionCreateRequest
        contentType: application/json
        schema: ${file(models/create-transaction-request.json)}
      - name: TransactionUpdateRequest
        contentType: application/json
        schema: ${file(models/update-transaction-request.json)}
  esLogs:
    endpoint: !GetAtt ImagesSearch.DomainEndpoint
    index: "logtrace-index"
    includeApiGWLogs: true
    indexDateSeparator: '-'

resources:
  - ${file(src/requests/validator.yml)}
  - ${file(src/dataLayer/dynamodb.yml)}
  - ${file(src/dataLayer/s3.yml)}
  - ${file(src/dataLayer/elasticSearch.yml)}